config/routes.rb
Rails.application.routes.draw do
  get 'read_content/read'
  get 'previous_rentals/list'
  delete 'previous_rentals/destroy'
  root 'index#index'
  resources :galleries
  resources :publishers
  resources :magazines
  resources :authors
  resources :books
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  # login/session routes
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'rent', to: 'books#rent_book', as: 'rent'
  post 'rent_magazine', to: 'magazines#rent_magazine', as: 'rent_magazine'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :author
  has_one_attached :image
  validates :title, :isbn, presence: true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    has_and_belongs_to_many :users
end

app/models/magazine.rb
class Magazine < ApplicationRecord
    has_and_belongs_to_many :users
    belongs_to :publisher
    has_one_attached :image
    validates :name, presence: true
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :magazine
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
    validates :password, :username, presence: true
    has_and_belongs_to_many :book, trough: :books_users
    has_and_belongs_to_many :magazine, trough: :magazine_users
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    @author.update_attributes(author_params)
    redirect_to :controller => 'authors', :action => 'index'
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:success] = "Author created succesfully!"
      redirect_to :controller => 'authors', :action => 'index'
    else
      flash[:error] = "Error while creating author!"
      render 'new'
    end
  end

  def destroy
    @author = Author.find(params[:id])
    if @author.destroy
      flash[:success] = "Author deleted succesfully!"
    else
      flash[:error] = "Error while deleting author!"
    end

    redirect_to :controller => 'authors', :action => 'index'
  end

  def author_params
    params.require(:author).permit(:name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @authors = Author.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update_attributes(book_params)
    redirect_to :controller => 'books', :action => 'index'
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "Book created succesfully!"
      redirect_to :controller => 'books', :action => 'index'
    else
      flash[:error] = "Error while creating book!"
      render 'new'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:success] = "Book deleted succesfully!"
    else
      flash[:error] = "Error while deleting book!"
    end

    redirect_to :controller => 'books', :action => 'index'
  end

  def book_params
    params.require(:book).permit(:title, :isbn, :author_id, :image, :description)
  end

  def rent_book
    user = User.find(current_user.id)
    book = Book.find(params[:id])
    if user.book.include?(book)
      flash[:error] = "Book is alredy rented!"
      redirect_to books_path
    else
      if user.book << book
        flash[:success] = "Book rented succesfully!"
        redirect_to :controller => 'previous_rentals', :action => 'list'
      else
        flash[:error] = "Book rental error!"
      end
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Registration succeed!"
      redirect_to login_path
    else
      flash[:error] = "Registration error!"
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = "User deleted succesfully!"
    else
      flash[:error] = "Error while deleting book!"
    end

    redirect_to :controller => 'users', :action => 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/previous_rentals_helper.rb
module PreviousRentalsHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/read_content_helper.rb
module ReadContentHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/delete.html.erb
<h1>Authors#delete</h1>
<p>Find me in app/views/authors/delete.html.erb</p>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>
<%= simple_form_for @author do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, "Save", class: "btn-primary" %>
<% end %>

app/views/authors/index.html.erb
<div class="row">
  <div class="col-md-4">
    <h1>List of Authors</h1>
  </div>
  <div class="col-md-2 offset-md-6 text-right my-auto">
    <%= link_to '<button class="btn btn-success">
            Create
        </button>'.html_safe, "/authors/new" %>
  </div>
</div>
<table id="books_table" class="table table-striped table-bordered">
  <thead class="thead-dark">
  <tr>
    <th scope="col">Name</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @authors.each do |author| %>
    <tr>
      <td><%= link_to(author.name, edit_author_path(author)) %></td>
      <td><%= link_to 'Delete',
                      author_path(author),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/authors/list.html.erb
<h1>Authors#list</h1>
<p>Find me in app/views/authors/list.html.erb</p>

app/views/authors/new.html.erb
<h1>Create Author</h1>
<%= simple_form_for @author, multipart: true do |f| %>
  <%= f.input :name, required: true %>
  <%= f.button :submit, "Create Author", class: "btn-primary" %>
<% end %>

app/views/authors/show.html.erb
<h1>Edit Author</h1>
<%= simple_form_for @author do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, "Save", class: "btn-primary" %>
<% end %>

app/views/books/delete.html.erb
<h1>Books#delete</h1>
<p>Find me in app/views/books/delete.html.erb</p>

app/views/books/edit.html.erb
<style type="text/css">
  /*****************globals*************/

  .custom_wrapper {
    font-family: 'open sans';
    overflow-x: hidden;
  }
  img {
    max-width: 100%; }

  .preview {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -webkit-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column; }
  @media screen and (max-width: 996px) {
    .preview {
      margin-bottom: 20px; } }

  .preview-pic {
    -webkit-box-flex: 1;
    -webkit-flex-grow: 1;
    -ms-flex-positive: 1;
    flex-grow: 1; }

  .preview-thumbnail.nav-tabs {
    border: none;
    margin-top: 15px; }
  .preview-thumbnail.nav-tabs li {
    width: 18%;
    margin-right: 2.5%; }
  .preview-thumbnail.nav-tabs li img {
    max-width: 100%;
    display: block; }
  .preview-thumbnail.nav-tabs li a {
    padding: 0;
    margin: 0; }
  .preview-thumbnail.nav-tabs li:last-of-type {
    margin-right: 0; }

  .tab-content {
    overflow: hidden; }
  .tab-content img {
    width: 100%;
    -webkit-animation-name: opacity;
    animation-name: opacity;
    -webkit-animation-duration: .3s;
    animation-duration: .3s; }

  .card {
    margin-top: 10px;
    background: #eee;
    padding: 3em;
    line-height: 1.5em; }

  @media screen and (min-width: 997px) {
    .wrapper {
      display: -webkit-box;
      display: -webkit-flex;
      display: -ms-flexbox;
      display: flex; } }

  .details {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -webkit-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column; }

  .colors {
    -webkit-box-flex: 1;
    -webkit-flex-grow: 1;
    -ms-flex-positive: 1;
    flex-grow: 1; }

  .product-title, .price, .sizes, .colors {
    text-transform: UPPERCASE;
    font-weight: bold; }

  .checked, .price span {
    color: #ff9f1a; }

  .product-title, .rating, .product-description, .price, .vote, .sizes {
    margin-bottom: 15px; }

  .product-title {
    margin-top: 0; }

  .size {
    margin-right: 10px; }
  .size:first-of-type {
    margin-left: 40px; }

  .color {
    display: inline-block;
    vertical-align: middle;
    margin-right: 10px;
    height: 2em;
    width: 2em;
    border-radius: 2px; }
  .color:first-of-type {
    margin-left: 20px; }

  .add-to-cart, .like {
    background: #ff9f1a;
    padding: 1.2em 1.5em;
    border: none;
    text-transform: UPPERCASE;
    font-weight: bold;
    color: #fff;
    -webkit-transition: background .3s ease;
    transition: background .3s ease; }
  .add-to-cart:hover, .like:hover {
    background: #b36800;
    color: #fff; }

  .not-available {
    text-align: center;
    line-height: 2em; }
  .not-available:before {
    font-family: fontawesome;
    content: "\f00d";
    color: #fff; }

  .orange {
    background: #ff9f1a; }

  .green {
    background: #85ad00; }

  .blue {
    background: #0076ad; }

  .tooltip-inner {
    padding: 1.3em; }

  @-webkit-keyframes opacity {
    0% {
      opacity: 0;
      -webkit-transform: scale(3);
      transform: scale(3); }
    100% {
      opacity: 1;
      -webkit-transform: scale(1);
      transform: scale(1); } }

  @keyframes opacity {
    0% {
      opacity: 0;
      -webkit-transform: scale(3);
      transform: scale(3); }
    100% {
      opacity: 1;
      -webkit-transform: scale(1);
      transform: scale(1); } }

</style>


<div class="custom_wrapper">
  <div class="row mt-3">
    <div class="col-md-12">
      <h1>Edit Book</h1>
    </div>
  </div>
  <div class="row">
    <%= simple_form_for @book, multipart: true do |f| %>
      <div class="container">
        <div class="card">
          <div class="container-fliud">
            <div class="wrapper row">
              <div class="preview col-md-6">

                <div class="preview-pic tab-content">
                  <div class="tab-pane active" id="pic-1"><%= image_tag(@book.image, :class => "rounded") if @book.image.attached? %></div>
                  <%= f.file_field :image %>
                </div>
              </div>
              <div class="details col-md-6">
                <h3 class="product-title"><%= f.input :title %></h3>
                <%= f.association :author %>
                <p><%= f.input :isbn %></p>
                <p class="product-description"><%= f.input :description, as: :text %></p>
                <h4 class="price">current price: <span>$180</span></h4>
                <p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>
                <div class="action mt-2">
                  <button class=" btn btn-secondary btn-lg" type="button">Cancel</button>
                  <%= f.button :submit, "Save", class: "btn btn-success btn-lg" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<div class="row">
    <div class="col-md-4">
        <h1>List of Books</h1>
    </div>
    <div class="col-md-2 offset-md-6 text-right my-auto">
    <%= link_to '<button class="btn btn-success">
            Create
        </button>'.html_safe, "/books/new" %>
    </div>
</div>
<table id="books_table" class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Cover</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Isbn</th>
      <th scope="col">Description</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= image_tag(book.image, :class => "thumbnail rounded") if book.image.attached? %></td>
        <td><%= link_to(book.title, book) %></td>
        <td><%= link_to(book.author.name, book.author) if !book.author.nil? %></td>
        <td><%= book.isbn %></td>
        <td class="more"><%= book.description %></td>
        <td><%= link_to 'Delete',
                         book_path(book),
                         method: :delete,
                         data: { confirm: 'Are you sure?' } %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/list.html.erb
<h1>Books#list</h1>
<p>Find me in app/views/books/list.html.erb</p>

app/views/books/new.html.erb
<h1>Create new Book</h1>
<%= simple_form_for @book, multipart: true do |f| %>
    <%= f.input :title, required: false %>
    <%= f.input :isbn, required: true %>
    <%= f.input :description, as: :text %>
    <%= f.association :author, required: true %>
    <%= f.file_field :image %>
    <%= f.button :submit, "Create Book", class: "btn-primary" %>
<% end %>

app/views/books/show.html.erb
<style type="text/css">
  /*****************globals*************/
  body {
    font-family: 'open sans';
    overflow-x: hidden; }

  img {
    max-width: 100%; }

  .preview {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -webkit-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column; }
  @media screen and (max-width: 996px) {
    .preview {
      margin-bottom: 20px; } }

  .preview-pic {
    -webkit-box-flex: 1;
    -webkit-flex-grow: 1;
    -ms-flex-positive: 1;
    flex-grow: 1; }

  .preview-thumbnail.nav-tabs {
    border: none;
    margin-top: 15px; }
  .preview-thumbnail.nav-tabs li {
    width: 18%;
    margin-right: 2.5%; }
  .preview-thumbnail.nav-tabs li img {
    max-width: 100%;
    display: block; }
  .preview-thumbnail.nav-tabs li a {
    padding: 0;
    margin: 0; }
  .preview-thumbnail.nav-tabs li:last-of-type {
    margin-right: 0; }

  .tab-content {
    overflow: hidden; }
  .tab-content img {
    width: 100%;
    -webkit-animation-name: opacity;
    animation-name: opacity;
    -webkit-animation-duration: .3s;
    animation-duration: .3s; }

  .card {
    margin-top: 50px;
    background: #eee;
    padding: 3em;
    line-height: 1.5em; }

  @media screen and (min-width: 997px) {
    .wrapper {
      display: -webkit-box;
      display: -webkit-flex;
      display: -ms-flexbox;
      display: flex; } }

  .details {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -webkit-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column; }

  .colors {
    -webkit-box-flex: 1;
    -webkit-flex-grow: 1;
    -ms-flex-positive: 1;
    flex-grow: 1; }

  .product-title, .price, .sizes, .colors {
    text-transform: UPPERCASE;
    font-weight: bold; }

  .checked, .price span {
    color: #ff9f1a; }

  .product-title, .rating, .product-description, .price, .vote, .sizes {
    margin-bottom: 15px; }

  .product-title {
    margin-top: 0; }

  .size {
    margin-right: 10px; }
  .size:first-of-type {
    margin-left: 40px; }

  .color {
    display: inline-block;
    vertical-align: middle;
    margin-right: 10px;
    height: 2em;
    width: 2em;
    border-radius: 2px; }
  .color:first-of-type {
    margin-left: 20px; }

  .add-to-cart, .like {
    background: #ff9f1a;
    padding: 1.2em 1.5em;
    border: none;
    text-transform: UPPERCASE;
    font-weight: bold;
    color: #fff;
    -webkit-transition: background .3s ease;
    transition: background .3s ease; }
  .add-to-cart:hover, .like:hover {
    background: #b36800;
    color: #fff; }

  .not-available {
    text-align: center;
    line-height: 2em; }
  .not-available:before {
    font-family: fontawesome;
    content: "\f00d";
    color: #fff; }

  .orange {
    background: #ff9f1a; }

  .green {
    background: #85ad00; }

  .blue {
    background: #0076ad; }

  .tooltip-inner {
    padding: 1.3em; }

  @-webkit-keyframes opacity {
    0% {
      opacity: 0;
      -webkit-transform: scale(3);
      transform: scale(3); }
    100% {
      opacity: 1;
      -webkit-transform: scale(1);
      transform: scale(1); } }

  @keyframes opacity {
    0% {
      opacity: 0;
      -webkit-transform: scale(3);
      transform: scale(3); }
    100% {
      opacity: 1;
      -webkit-transform: scale(1);
      transform: scale(1); } }

</style>

<div class="container">
  <div class="card">
    <div class="container-fliud">
      <div class="wrapper row">
        <div class="preview col-md-6">

          <div class="preview-pic tab-content">
            <div class="tab-pane active" id="pic-1"><%= image_tag(@book.image, :class => "rounded") if @book.image.attached? %></div>
          </div>
        </div>
        <div class="details col-md-6">
          <h3 class="product-title"><%= @book.title %></h3>
          <div class="rating">
            <div class="stars">
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
            </div>
            <span class="review-no">41 reviews</span>
          </div>
          <p class="product-description"><%= @book.description %></p>
          <h4 class="price">current price: <span>$180</span></h4>
          <p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>
          <% if current_user %>
            <div class="action">
              <%= link_to 'Rent this book', rent_path(:id => @book.id), :method => :post, class: 'add-to-cart btn btn-default' %>
            </div>
          <% end %>
          <div class="action mt-2">
            <%= link_to '<button class="btn btn-info btn-lg">
                            Edit
                          </button>'.html_safe, "/books/#{@book.id}/edit" %>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-4">
    <h1>List of Users</h1>
  </div>
</div>
<table id="books_table" class="table table-striped table-bordered">
  <thead class="thead-dark">
  <tr>
    <th scope="col">Username</th>
    <th scope="col">Email</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to(user.username, user) %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Delete',
                      user_path(user),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Registration</h1>
<%= simple_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.input :email %>
  <%= f.button :submit, "Registration", class: "btn-primary" %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>