config/routes.rb
Rails.application.routes.draw do
  get 'read_content/read'
  get 'previous_rentals/list'
  delete 'previous_rentals/destroy'
  root 'index#index'
  resources :galleries
  resources :publishers
  resources :magazines
  resources :authors
  resources :books
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  # login/session routes
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'rent', to: 'books#rent_book', as: 'rent'
  post 'rent_magazine', to: 'magazines#rent_magazine', as: 'rent_magazine'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :author
  has_one_attached :image
  validates :title, :isbn, presence: true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    has_and_belongs_to_many :users
end

app/models/magazine.rb
class Magazine < ApplicationRecord
    has_and_belongs_to_many :users
    belongs_to :publisher
    has_one_attached :image
    validates :name, presence: true
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :magazine
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
    validates :password, :username, presence: true
    has_and_belongs_to_many :book, trough: :books_users
    has_and_belongs_to_many :magazine, trough: :magazine_users
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @authors = Author.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update_attributes(book_params)
    redirect_to :controller => 'books', :action => 'index'
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "Book created succesfully!"
      redirect_to :controller => 'books', :action => 'index'
    else
      flash[:error] = "Error while creating book!"
      render 'new'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:success] = "Book deleted succesfully!"
    else
      flash[:error] = "Error while deleting book!"
    end

    redirect_to :controller => 'books', :action => 'index'
  end

  def book_params
    params.require(:book).permit(:title, :isbn, :author_id, :image, :description)
  end

  def rent_book
    user = User.find(current_user.id)
    book = Book.find(params[:id])
    if user.book.include?(book)
      flash[:error] = "Book is alredy rented!"
      redirect_to books_path
    else
      if user.book << book
        flash[:success] = "Book rented succesfully!"
        redirect_to :controller => 'previous_rentals', :action => 'list'
      else
        flash[:error] = "Book rental error!"
      end
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Registration succeed!"
      redirect_to login_path
    else
      flash[:error] = "Registration error!"
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = "User deleted succesfully!"
    else
      flash[:error] = "Error while deleting book!"
    end

    redirect_to :controller => 'users', :action => 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/read_content_helper.rb
module ReadContentHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/index.html.erb
<main role="main">

      <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Library On Rails</h1>
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non lobortis diam. Suspendisse finibus suscipit neque sed aliquam. Pellentesque facilisis sagittis pulvinar. Cras elit nunc, hendrerit id convallis vitae, aliquet accumsan magna.</p>
    </div>

      <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="wrapper">
                  <img class="card-img-top img-fluid" src="https://s03.static.libri.hu/cover/21/f/5076205_3.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="wrapper">
                  <img class="card-img-top img-fluid" src="https://s04.static.libri.hu/cover/25/e/5326731_3.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="wrapper">
                  <img class="card-img-top img-fluid" src="https://s05.static.libri.hu/cover/b6/f/716048_3.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="wrapper">
                  <img class="card-img-top img-fluid" src="https://s02.static.libri.hu/cover/cc/9/5241276_3.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="wrapper">
                 <img class="card-img-top img-fluid" src="https://s05.static.libri.hu/cover/87/7/5325383_3.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="wrapper">
                  <img class="card-img-top img-fluid" src="https://s02.static.libri.hu/cover/8b/a/5185442_3.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="wrapper">
                  <img class="card-img-top img-fluid" src="https://s04.static.libri.hu/cover/61/f/781672_5.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="wrapper">
                  <img class="card-img-top img-fluid" src="https://s01.static.libri.hu/cover/6b/c/5238112_3.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="wrapper">
                  <img class="card-img-top img-fluid" src="https://s04.static.libri.hu/cover/ac/9/5157642_3.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="site-header sticky-top py-1">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        <a class="py-2" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mx-auto"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
        </a>
        <% if current_user %>
          <a href="#" class="py-2 d-none d-md-inline-block">Welcome back <%= current_user.username %> </a>
        <% else %>
          <%= link_to "Sign Up", signup_path, class: "py-2 d-none d-md-inline-block" %>
          <%= link_to "Log In", login_path, class: "py-2 d-none d-md-inline-block" %>
        <% end %>
        <div class="dropdown show">
          <a class="py-2 d-none d-md-inline-block dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= t 'navbar.models' %>
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <%= link_to t('navbar.model_list.books'), "/books" , class: "dropdown-item" %>
            <%= link_to t('navbar.model_list.authors'), "/authors" , class: "dropdown-item" %>
            <%= link_to t('navbar.model_list.magazines'), "/magazines" , class: "dropdown-item" %>
            <%= link_to t('navbar.model_list.galleries'), "/galleries" , class: "dropdown-item" %>
            <%= link_to t('navbar.model_list.publishers'), "/publishers" , class: "dropdown-item" %>
            <%= link_to t('navbar.model_list.users'), "/users" , class: "dropdown-item" %>
          </div>
        </div>

        <%= link_to "Previous rentals", previous_rentals_list_path, class: "py-2 d-none d-md-inline-block" if current_user%>
        <a class="py-2 d-none d-md-inline-block" href="#">Support</a>
        <a class="py-2 d-none d-md-inline-block" href="#">EN</a>
        <a class="py-2 d-none d-md-inline-block" href="#"></a>
        <% if current_user %>
          <%= link_to "Log Out", logout_path, class: "py-2 d-none d-md-inline-block" %>
        <% end %>
      </div>
    </nav>
    <% unless flash.empty? %>
      <script type="text/javascript">
        <% flash.each do |f| %>
          <% type = f[0].gsub('alert', 'error').gsub('notice', 'info') %>
          toastr['<%= type %>']('<%= f[1] %>', '<%= type %>');
        <% end %>
      </script>
    <% end %>
    <div id="modal-holder"></div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>